#
#   asm module makefile
#   
#   This file is part of the toolchain to compile the asm module
#
#
#    @file:      $File$
#    @author:    $Author$
#    @date:      $Date$
#    @version:   $Revision$
#
#    $Id$
#
#
#   (C) Copyright 2016 Filippo Giuliani <mail@filippogiuliani.it>
#
#   This file is part of kembed.
#
#   kembed is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   kembed is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with kembed.  If not, see <http://www.gnu.org/licenses/>.


KEMBED_ROOT := ..
include $(KEMBED_ROOT)/Make.def

all :
	$(HIDE)$(MAKE) -C src $(MFLAGS) all $(FOUT)

clean : 
	$(HIDE)$(MAKE) -C src $(MFLAGS) clean $(FOUT)
